### ISSUE TITLE
PlatformIO了解一下

### ISSUE THREAD

**Issue by LeoJhonSong** [wmdscjhdpy/VSCode-STM32-Development#1]
老兄如果你喜欢在VSC里开发嵌入式推荐了解一下[PlatformIO](https://marketplace.visualstudio.com/items?itemName=platformio.platformio-ide)这个插件:+1:

它支持极其丰富的种类的板子而且因为基本是python写成的所以Windows/Linux/Mac都可以用这个插件

**Comment by wmdscjhdpy** [comment]
感觉是个好东西！谢谢你的推荐~
